version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: db.dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: upgrade
